org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true
gradle.user.home=/home/user/.gradle
org.gradle.caching=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
